/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

/*
 * File: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@class NSHTTPCookieDiskStoragePrivate;

@interface NSHTTPCookieDiskStorage : NSObject
{
    NSHTTPCookieDiskStoragePrivate *_serverPrivate;
}

- (void)dealloc;
- (void)finalize;
- (void)setCookies:(id)fp8 whilePrivateBrowsing:(BOOL)fp12;
- (void)deleteCookies:(id)fp8;
- (void)purgeCookiesFromPrivateBrowsing;
- (id)cookies;
- (void)_tryCookieLookup:(id)fp8 path:(id)fp12 secure:(BOOL)fp16 result:(id)fp20;
- (id)cookiesMatchingDomain:(id)fp8 path:(id)fp12 secure:(BOOL)fp16;
- (id)init;
- (id)initWithNotificationObject:(id)fp8;

@end

@interface NSHTTPCookieDiskStoragePrivate : NSObject
{
    struct __CFRunLoopTimer *expirationTimer;
    NSMutableDictionary *lastReadKeyToCookie;
    NSMutableDictionary *locallyAddedKeyToCookie;
    NSMutableSet *locallyDeletedCookies;
    NSMutableSet *locallyDeletedKeys;
    NSDictionary *cookiesCache;
    id notificationObject;
    BOOL saveCookiesScheduled;
    BOOL notificationScheduled;
    BOOL cookiesCacheIsValid;
    BOOL cookiesCacheNeedsReading;
    struct __CFRunLoopTimer *saveTimer;
    NSLock *lock;
    NSLock *notificationLock;
}

- (id)init;
- (void)dealloc;
- (void)finalize;

@end

@interface NSHTTPCookieDiskStorage (NSInternal)
- (void)_notifyLocalCookiesChanged:(id)fp8;
- (void)_scheduleLocalNotification;
- (void)_checkForCookieExpiration;
- (void)_updateExpirationTimer:(double)fp8;
- (void)_saveCookies;
- (id)_pidString;
- (void)_syncCookies:(id)fp8;
- (void)_clearSaveTimer;
- (void)_saveCookiesIfScheduled;
- (void)_scheduleSaveCookies;
- (void)_notifyCookiesSynced;
- (BOOL)_setLoadedCookiesWithoutSaving:(id)fp8;
- (BOOL)_setCookiesWithoutSaving:(id)fp8 whilePrivateBrowsing:(BOOL)fp12;
@end

