/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

/*
 * File: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 */

@class NSHTTPCookieDiskStorage;
@class NSURLRecursiveReadWriteLock;
@class NSURLMonitor;

@interface NSHTTPCookieStorageInternal : NSObject
{
    NSHTTPCookieDiskStorage *storage;
    int acceptCookiesPolicy;
    NSTimer *expirationTimer;
    NSURLRecursiveReadWriteLock *dataLock;
    NSURLMonitor *setupMonitor;
    BOOL didSetup;
    BOOL expirationTimerSet;
    BOOL privateBrowsing;
    BOOL _pad2;
}

- (id)init;
- (void)dealloc;
- (void)finalize;

@end

@interface NSHTTPCookieStorage (NSPrivate)
- (id)_cookieRequestHeaderFieldsForURL:(id)fp8 withExtraCookies:(id)fp12;
- (id)_cookiesForURL:(id)fp8 withExtraCookies:(id)fp12;
- (void)_setPrivateBrowsingEnabled:(BOOL)fp8;
@end

@interface NSHTTPCookieStorage (NSInternal)
+ (BOOL)_allowedToSetCookiesFromURL:(id)fp8 withPolicyBaseURL:(id)fp12;
- (void)_readAcceptCookiesPreference;
- (void)_registerForCookiePreferenceNotification;
- (void)_connectToCookieStorage;
- (void)_scheduleSetupOnLoadThread;
- (void)_waitForLoadThreadSetup;
- (void)_setCookies:(id)fp8 forURL:(id)fp12 policyBaseURL:(id)fp16;
- (id)_internalInit;
@end

