#define BundleIdentifier								@"com.sweetpproductions.SafariCookies"
#define SCCookiesPath									@"~/Library/Cookies/Cookies.plist"
#define SCApplicationSupportFolderPath					@"~/Library/Application Support/Safari Cookies"
#define SCFavoriteDomainsPlistFullName					@"Favorites.plist"

#define SCPreferencesCookieAcceptPolicy					@"SCcookieAcceptPolicy"
#define SCPreferencesRemoveNonFavoritesWhenQuitting		@"SCremoveNonFavoritesWhenQuitting"
#define SCPreferencesShouldLogActivity					@"SCenableLogging"
#define SCPreferencesTabStateKey						@"SCtabState"
#define SCPreferencesRemoveAllAlertsKey					@"SCdontShowRemoveAllAlert"
#define SCPreferencesExportAlertKey						@"SCdontShowExportAlert"
#define SCPreferencesImportAlertKey						@"SCdontShowImportAlert"