#!/bin/sh


# remove unneeded defaults
#find all users
for arg in `ls /Users`
do

#copy preferences for all users, if they exists - ignoring the Shared folder
if [ $arg != 'Shared' ]; then
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCautomaticUpdating \`/usr/bin/defaults read com.apple.Safari SCautomaticUpdating\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCcookieAcceptPolicy \`/usr/bin/defaults read com.apple.Safari SCcookieAcceptPolicy\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCtabState \`/usr/bin/defaults read com.apple.Safari SCtabState\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCdontShowRemoveAllAlert \`/usr/bin/defaults read com.apple.Safari SCdontShowRemoveAllAlert\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCdontShowRemoveFlashAlert \`/usr/bin/defaults read com.apple.Safari SCdontShowRemoveFlashAlert\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCdontShowExportAlert \`/usr/bin/defaults read com.apple.Safari SCdontShowExportAlert\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCdontShowImportAlert \`/usr/bin/defaults read com.apple.Safari SCdontShowImportAlert\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCdontShowImportFromBookmarksAlert \`/usr/bin/defaults read com.apple.Safari SCdontShowImportFromBookmarksAlert\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCdontShowImportFromTopSitesAlert \`/usr/bin/defaults read com.apple.Safari SCdontShowImportFromTopSitesAlert\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCdontShowImportFromHistoryAlert \`/usr/bin/defaults read com.apple.Safari SCdontShowImportFromHistoryAlert\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCautomaticMode \`/usr/bin/defaults read com.apple.Safari SCautomaticMode\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCremoveGoogleAnalyticsCookiesWhenQuitting \`/usr/bin/defaults read com.apple.Safari SCremoveGoogleAnalyticsCookiesWhenQuitting\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCautoKeepBookmarks \`/usr/bin/defaults read com.apple.Safari SCautoKeepBookmarks\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCautoKeepTopSites \`/usr/bin/defaults read com.apple.Safari SCautoKeepTopSites\`"
	/usr/bin/su $arg -c "/usr/bin/defaults write com.sweetpproductions.SafariCookies SCautoKeepHistory \`/usr/bin/defaults read com.apple.Safari SCautoKeepHistory\`"

#remove unused preferences for all users, if they exists - ignoring the Shared folder
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCremoveFlashCookiesWhenQuitting"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCremoveNonFavoritesWhenQuitting"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCautomaticUpdating"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCcookieAcceptPolicy"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCtabState"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCdontShowRemoveAllAlert"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCdontShowRemoveFlashAlert"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCdontShowExportAlert"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCdontShowImportAlert"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCdontShowImportFromBookmarksAlert"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCdontShowImportFromTopSitesAlert"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCdontShowImportFromHistoryAlert"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCautomaticMode"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCremoveGoogleAnalyticsCookiesWhenQuitting"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCautoKeepBookmarks"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCautoKeepTopSites"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCautoKeepHistory"
fi
done
exit 0