#!/bin/sh


# remove unneeded defaults
#find all users
for arg in `ls /Users`
do

#remove unused preference for all users, if it exists - ignoring the Shared folder
if [ $arg != 'Shared' ]; then
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCremoveFlashCookiesWhenQuitting"
	/usr/bin/su $arg -c "/usr/bin/defaults delete com.apple.Safari SCremoveNonFavoritesWhenQuitting"
fi
done
exit 0