#define BundleIdentifier								@"com.sweetpproductions.SafariCookies"

#define SCCookiesPath									@"~/Library/Cookies/Cookies.plist"
#define SCApplicationSupportFolderPath					@"~/Library/Application Support/Safari Cookies"
#define SCFlashCookiesPath								@"~/Library/Preferences/Macromedia/Flash Player"
#define SCFavoriteDomainsPlistFullName					@"Favorites.plist"

#define SCPreferencesCookieAcceptPolicy					@"SCcookieAcceptPolicy"
#define SCPreferencesAutomaticMode						@"SCautomaticMode"
#define SCPreferencesRemoveNonFavoritesWhenQuitting		@"SCremoveNonFavoritesWhenQuitting"
#define SCPreferencesRemoveFlashCookiesWhenQuitting		@"SCremoveFlashCookiesWhenQuitting"
#define SCPreferencesRemoveGoogleAnalyticsCookies		@"SCremoveGoogleAnalyticsCookiesWhenQuitting"
#define SCPreferencesShouldCheckForUpdates				@"SCautomaticUpdating"

#define SCPreferencesTabStateKey						@"SCtabState"
#define SCPreferencesRemoveAllAlertKey					@"SCdontShowRemoveAllAlert"
#define SCPreferencesExportAlertKey						@"SCdontShowExportAlert"
#define SCPreferencesImportAlertKey						@"SCdontShowImportAlert"
#define SCPreferencesImportFromBookmarksAlertKey		@"SCdontShowImportFromBookmarksAlert"
#define SCPreferencesImportFromTopSitesAlertKey			@"SCdontShowImportFromTopSitesAlert"
#define SCPreferencesImportFromHistoryAlertKey			@"SCdontShowImportFromHistoryAlert"

#define SafariSupportFolderPath							@"~/Library/Safari"
#define SafariBookmarksPlistFullName					@"Bookmarks.plist"
#define SafariTopSitesPlistFullName						@"TopSites.plist"
#define SafariHistoryPlistFullName						@"History.plist"